# Generated by Django 4.0.4 on 2023-01-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=2)),
                ('Pokemon_Type', models.CharField(choices=[('WA', 'Water'), ('GR', 'grass'), ('GH', 'ghoste'), ('ST', 'steel'), ('FA', 'fairy')], max_length=100)),
                ('hp', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('name_fr', models.CharField(blank=True, default='', max_length=30)),
                ('name_ar', models.CharField(blank=True, default='', max_length=30)),
                ('name_jp', models.CharField(blank=True, default='', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
